name: Munan
description: "Clear-up DeepLearning"
baseurl: .
url: http://fabulousjeong.github.io
download: "https://github.com/fabulousjeong/fabulousjeong.github.io/archive/master.zip"
social:
  github: fabulousjeong
  email: fabulousjeong@gmail.com
  facebook: fabulousjeong
  twitter:
  instagram: munan0614
  tumblr:
author:
  name: Munan Jeong
  bio: "Senior Deeplearning and Graphics Developer"
  email: fabulousjeong@gmail.com
  image: /assets/images/author.jpg
  github: fabulousjeong
  facebook: fabulousjeong
  twitter:
  instagram: munan0614
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor
